# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json

name: origami-linux

description: "Origami is a next-generation Linux distribution inspired by the art of Japanese paper folding. Built on Fedora Atomic with Universal Blue, Origami elegantly folds together cutting-edge tools, beautiful design, and thoughtful defaults to create a lightweight, customizable, and visually stunning operating system using the Cosmic desktop environment. With a focus on simplicity, speed, and creativity, Origami empowers users to shape their digital environment as effortlessly as folding a masterpiece."

base-image: ghcr.io/ublue-os/base-main
image-version: latest
modules:

  - type: dnf
    repos:
      cleanup: true
      copr:
        - dejan/lazygit
        - lihaohong/yazi
        - alternateved/eza
        - atim/starship
        - dejan/rpms
      files:
        - https://pkg.cloudflareclient.com/cloudflare-warp-ascii.repo
      keys:
        - https://pkg.cloudflareclient.com/pubkey.gpg

    install:
      packages:
        - '@cosmic-desktop-environment'
        - cloudflare-warp
        - btop
        - fastfetch
        - podman-compose
        - java
        - bat
        - ripgrep
        - zoxide
        - lazygit
        - yazi
        - eza
        - hyperfine
        - starship
        - cbonsai
        - cmatrix
        - tty-clock
        - sudo-rs
        - uutils-coreutils

    #remove:
      #auto-remove: true
      #packages:
        #- htop
        #- nvtop
        #- firefox
        #- firefox-langpacks
        #- gnome-disk-utility
        #- gnome-system-monitor
        #- ark
        #- ark-libs
        #- cosmic-player

  - type: fonts
    fonts:
      nerd-fonts:
        - JetBrainsMono
      google-fonts:
        - Inter

  - type: files
    files:
      - source: system
        destination: /

  - type: script
    snippets:
      - glib-compile-schemas /usr/share/glib-2.0/schemas/
      - git clone https://github.com/vinceliuice/WhiteSur-icon-theme.git /tmp/WhiteSur-icon-theme
      - /tmp/WhiteSur-icon-theme/install.sh -b -a
      - rm -rf /tmp/WhiteSur-icon-theme
      - grep -E '^greetd:' /usr/etc/passwd | sudo tee -a /etc/passwd
      - grep -E '^cosmic-greeter:' /usr/etc/passwd | sudo tee -a /etc/passwd
      - grep -E '^greetd:' /usr/etc/group | sudo tee -a /etc/group
      - grep -E '^cosmic-greeter:' /usr/etc/group | sudo tee -a /etc/group

  - type: os-release
    properties:
      ID: origami_Linux
      NAME: Origami Linux
      PRETTY_NAME: Origami 折り紙
      HOME_URL: "https://github.com/john-holt4/Origami"
      BUG_REPORT_URL: "https://github.com/john-holt4/Origami/issues"

  - type: initramfs

  - type: signing
