# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
#
# Name of your image
name: origami

# A short description of your image
description: "A custom Fedora Cosmic image. Folds in cloudflare-warp"

# The base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/cosmic-atomic-main
image-version: latest # This will track the latest stable release

modules:
  #
  # RPM/OSTREE CONFIGURATION
  #
  - type: rpm-ostree
    repos:
      # Add the repo for Cloudflare Warp
      - https://pkg.cloudflareclient.com/cloudflare-warp-ascii.repo
    keys:
      # Import the GPG key for the Cloudflare repo
      - https://pkg.cloudflareclient.com/pubkey.gpg
    
    install:
      # Cloudflare
      - cloudflare-warp
      
      # Your layered tools
      - btop
      - fastfetch
      - podman-compose
      - java
      - fzf
      
    remove:
      # Your list of removed packages
      - htop
      - nvtop
      - firefox
      - firefox-langpacks
      - gnome-disk-utility
      - gnome-system-monitor
      - ark
      - ark-libs

    type: fonts
    fonts:
      nerd-fonts:
        - JetBrainsMono
      google-fonts:
        - Inter

  #
  # ADD CUSTOM ALIASES & SHELL CONFIG
  #
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: script
    snippets:
      - sed -i 's/WatermarkVerticalAlignment=.*/WatermarkVerticalAlignment=2/g' /usr/share/plymouth/themes/bgrt/bgrt.plymouth

  - type: os-release
    properties:
      ID: origami_beta
      NAME: Origami
      PRETTY_NAME: Origami 折り紙
      HOME_URL: "https://github.com/john-holt4/Origami"
      BUG_REPORT_URL: "https://github.com/john-holt4/Origami/issues"

  - type: initramfs

  #
  # SIGNING
  #
  - type: signing
