# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
#
# Name of your image
name: origami

# A short description of your image
description: "A custom Fedora Cosmic image. Folds in cloudflare-warp, developer tools, and a curated Flatpak suite."

# The base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/cosmic-atomic-main
image-version: latest # This will track the latest stable release

modules:
  #
  # RPM/OSTREE CONFIGURATION
  #
  - type: rpm-ostree
    repos:
      # Add the repo for Cloudflare Warp
      - https://pkg.cloudflareclient.com/cloudflare-warp-ascii.repo
      # Add the repo for k6
      - https://dl.k6.io/rpm/k6.repo
    
    install:
      # Cloudflare
      - cloudflare-warp
      
      # Your layered tools
      - btop
      - eza
      - fastfetch
      - k6
      - podman-compose
      - java
      - starship
      - fzf
      
    remove:
      # Your list of removed packages
      - firefox
      - firefox-langpacks
      - gnome-disk-utility
      - gnome-system-monitor

  #
  # FLATPAK CONFIGURATION
  #
  - type: default-flatpaks
    configurations:
      - repos:
          # Add the COSMIC Flatpak repository
          cosmic:
            url: https://apt.pop-os.org/cosmic/
        
        # Install apps from Flathub (the default)
        install:
          - app.zen_browser.zen
          - com.github.tchx84.Flatseal
          - com.spotify.Client
          - com.visualstudio.code
          - com.vixalien.sticky
          - io.github.piotrek_k._2dTaskBoard
          - io.podman_desktop.PodmanDesktop
          - org.gnome.Loupe
          - org.onlyoffice.desktopeditors
          - us.zoom.Zoom

        # Install apps from the 'cosmic' repo we just added
        install-from:
          - repo: cosmic
            apps:
              - co.uk.cappsy.CosmicAppletLogoMenu
              - io.github.cosmic_utils.sysinfo-applet
          
  #
  # ADD CUSTOM ALIASES & SHELL CONFIG
  #
  - type: files
    files:
      # Copies the 'etc' folder from your repo into /etc/ on the image
      - source: etc
        destination: /

  #
  # SIGNING
  #
  - type: signing
