# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json

name: origami

description: "A custom Fedora Cosmic image. Folds in cloudflare-warp"

base-image: ghcr.io/ublue-os/cosmic-atomic-main
image-version: latest
modules:

  - type: dnf
    repos:
      copr:
        - dejan/lazygit
        - lihaohong/yazi
        - alternateved/eza
        - atim/starship
      files:
        - https://pkg.cloudflareclient.com/cloudflare-warp-ascii.repo
      keys:
        - https://pkg.cloudflareclient.com/pubkey.gpg

    install:
      packages:
        - cloudflare-warp
        - btop
        - fastfetch
        - podman-compose
        - java
        - bat
        - ripgrep
        - zoxide
        - lazygit
        - yazi
        - eza
        - hyperfine
        - starship

    remove:
      packages:
        - htop
        - nvtop
        - firefox
        - firefox-langpacks
        - gnome-disk-utility
        - gnome-system-monitor
        - ark
        - ark-libs

  - type: default-flatpaks
    configurations:

      - scope: user
        repo:
          title: Flathub
      - notify: false

      - scope: user
        repo:
          name: cosmic
          title: COSMIC
          url: https://apt.pop-os.org/cosmic-repo/cosmic.flatpakrepo
      - notify: false

        install:
          - co.uk.cappsy.CosmicAppletLogoMenu
          - io.github.cosmic_utils.sysinfo-applet

  - type: fonts
    fonts:
      nerd-fonts:
        - JetBrainsMono
      google-fonts:
        - Inter

  - type: files
    files:
      - source: system
        destination: /

  - type: script
    snippets:
      - glib-compile-schemas /usr/share/glib-2.0/schemas/
      - rm -f /etc/profile.d/colorls.sh
      - git clone https://github.com/vinceliuice/WhiteSur-icon-theme.git /tmp/WhiteSur-icon-theme
      - /tmp/WhiteSur-icon-theme/install.sh -b -a
      - rm -rf /tmp/WhiteSur-icon-theme
      - sudo sed -i '/\[Timer\]/a OnActiveSec=30s' /usr/lib/systemd/user/user-flatpak-setup.timer

  - type: systemd
    user:
      enabled:
        - user-flatpak-setup.timer

  - type: os-release
    properties:
      ID: origami_beta
      NAME: Origami
      PRETTY_NAME: Origami 折り紙
      HOME_URL: "https://github.com/john-holt4/Origami"
      BUG_REPORT_URL: "https://github.com/john-holt4/Origami/issues"

  - type: initramfs

  - type: signing
