# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
#
# Name of your image
name: origami

# A short description of your image
description: "A custom Fedora Cosmic image. Folds in cloudflare-warp, developer tools, and a curated Flatpak suite."

# The base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/cosmic-atomic-main
image-version: latest # This will track the latest stable release

modules:
  #
  # RPM/OSTREE CONFIGURATION
  #
  - type: rpm-ostree
    repos:
      # Add the repo for Cloudflare Warp
      - https://pkg.cloudflareclient.com/cloudflare-warp-ascii.repo
    keys:
      # Import the GPG key for the Cloudflare repo
      - https://pkg.cloudflareclient.com/pubkey.gpg
    
    install:
      # Cloudflare
      - cloudflare-warp
      
      # Your layered tools
      - btop
      - fastfetch
      - podman-compose
      - java
      - fzf
      
    remove:
      # Your list of removed packages
      - ark
      - htop
      - nvtop
          
  #
  # ADD CUSTOM ALIASES & SHELL CONFIG
  #
  - type: files
    files:
      # Copies the 'etc' folder from your repo into /etc/ on the image
      - source: etc
        destination: /

  - type: os-release
    properties:
      ID: origami_beta
      NAME: Oragami
      PRETTY_NAME: Oragami Image

  #
  # SIGNING
  #
  - type: signing
