# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json

#
# NAME & DESCRIPTION
#
name: Origami
description: "A custom Cosmic Atomic image. Folds in cloudflare-warp, developer tools, and a curated Flatpak suite."

#
# BASE IMAGE
#
base-image: ghcr.io/ublue-os/cosmic-atomic-main
image-version: latest

modules:
  #
  # RPM/OSTREE CONFIGURATION
  #
  - type: rpm-ostree
    repos:
      # Add the repo for Cloudflare Warp
      - https://pkg.cloudflareclient.com/cloudflare-warp-ascii.repo
    
    install:
      # Cloudflare
      - cloudflare-warp
      
      # Your layered tools
      - btop
      - eza
      - fastfetch
      - k6
      - podman-compose
      - java
      - starship
      - fzf
      
    remove:
      # Your list of removed packages
      - firefox
      - firefox-langpacks
      - gnome-disk-utility
      - gnome-system-monitor

  #
  # FLATPAK CONFIGURATION
  #
  - type: default-flatpaks
    repos:
      - name: cosmic
        url: https://apt.pop-os.org/cosmic/
        
    install:
      - app.zen_browser.zen
      - com.github.tchx84.Flatseal
      - com.spotify.Client
      - com.visualstudio.code
      - com.vixalien.sticky
      - io.github.piotrek_k._2dTaskBoard
      - io.podman_desktop.PodmanDesktop
      - org.gnome.Loupe
      - org.onlyoffice.desktopeditors
      - us.zoom.Zoom

    install-from:
      - repo: cosmic
        apps:
          - co.uk.cappsy.CosmicAppletLogoMenu
          - io.github.cosmic_utils.sysinfo-applet
          
  #
  # ADD CUSTOM ALIASES & SHELL CONFIG
  #
  - type: files
    files:
      - source: etc
        destination: /

  #
  # UB BATTERIES & SIGNING
  #
  - type: ublue-os/main
  - type: ublue-os/signing
