# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json

name: origami

description: "A custom Fedora Cosmic image. Folds in cloudflare-warp"

base-image: ghcr.io/ublue-os/cosmic-atomic-main
image-version: latest
modules:

  - type: dnf
    repos:
      cleanup: true
      copr:
        - dejan/lazygit
        - lihaohong/yazi
        - alternateved/eza
        - atim/starship
        - dejan/rpms
      files:
        - https://pkg.cloudflareclient.com/cloudflare-warp-ascii.repo
      keys:
        - https://pkg.cloudflareclient.com/pubkey.gpg

    install:
      packages:
        - cloudflare-warp
        - btop
        - fastfetch
        - podman-compose
        - java
        - bat
        - ripgrep
        - zoxide
        - lazygit
        - yazi
        - eza
        - hyperfine
        - starship
        - cbonsai
        - cmatrix
        - tty-clock

    remove:
      auto-remove: true
      packages:
        - htop
        - nvtop
        - firefox
        - firefox-langpacks
        - gnome-disk-utility
        - gnome-system-monitor
        - ark
        - ark-libs
        - cosmic-player

  - type: fonts
    fonts:
      nerd-fonts:
        - JetBrainsMono
      google-fonts:
        - Inter

  - type: files
    files:
      - source: system
        destination: /

  - type: script
    snippets:
      - glib-compile-schemas /usr/share/glib-2.0/schemas/
      - git clone https://github.com/vinceliuice/WhiteSur-icon-theme.git /tmp/WhiteSur-icon-theme
      - /tmp/WhiteSur-icon-theme/install.sh -b -a
      - rm -rf /tmp/WhiteSur-icon-theme
      - |
        cat <<EOF >> /etc/skel/.bashrc

        # --- Podman/Docker Aliases ---
        alias docker='podman'
        alias docker-compose='podman-compose'

        alias cat='bat'

        alias fastfetch='fastfetch -l /usr/share/fastfetch/presets/origami/origami-ascii.txt --logo-color-1 blue -c/usr/share/fastfetch/presets/origami/origami-fastfetch.jsonc'

        # eza aliases
        alias l='eza --icons'
        alias ls='eza --icons'                 # A "safe" override for interactive use
        alias ll='eza -l --icons'              # long list
        alias la='eza -la --icons'             # long list, all files
        alias l.='eza -la --ignore=.git --icons' # A good one for projects
        alias lt='eza --tree --level=2 --icons'  # tree view

        # --- Init functions ---
        
        # Set up fzf key bindings and fuzzy completion if fzf exists
        if command -v fzf &> /dev/null; then
          eval "\$(fzf --bash)" 
        fi
        
        # Set up zoxide if it exists
        if command -v zoxide &> /dev/null; then
          eval "\$(zoxide init bash)"
        fi
        
        # Set up starship prompt if it exists
        if command -v starship &> /dev/null; then
          # Ensure starship init runs only in interactive shells
          case "\$-" in
              *i*) eval "\$(starship init bash)" ;;
              *) ;;
          esac
        fi

        # --- Nag functions (Optional) ---
        
        # Nag user to use 'fd' instead of 'find' if fd exists
        if command -v fd &> /dev/null; then
          find() {
            echo "💡 Tip: Try using 'fd' next time for a simpler and faster search." >&2
            command find "\$@" 
          }
        fi

        # Nag user to use 'rg' instead of 'grep' if rg exists
        if command -v rg &> /dev/null; then
          grep() {
            if [[ -t 2 ]]; then
              echo "💡 Tip: Try using 'rg' for a simpler and faster search." >&2
            fi
            command grep "\$@" 
          }
        fi
        EOF

  - type: os-release
    properties:
      ID: origami_beta
      NAME: Origami
      PRETTY_NAME: Origami 折り紙
      HOME_URL: "https://github.com/john-holt4/Origami"
      BUG_REPORT_URL: "https://github.com/john-holt4/Origami/issues"

  - type: initramfs

  - type: signing
